### ISSUE TITLE
WebGPU doesn't work on versions of deno >= 1.32

### ISSUE THREAD

**Issue by sigmaxipi** [denoland/webgpu-examples#13]
Creating this issue to help others who run into the same error:
```
error: Uncaught ReferenceError: GPUTextureUsage is not defined
const basic = GPUTextureUsage.COPY_SRC | GPUTextureUsage.COPY_DST |
```

https://github.com/denoland/deno/pull/18094 removed support for webgpu in version 1.32. `deno upgrade --version 1.31.3` needs to be run before the examples can be used

**Comment by crowlKats** [comment]
FYI we are currently investigating bringing WebGPU back

**Comment by jsejcksn** [comment]
> FYI we are currently investigating bringing WebGPU back

@crowlKats Where can one subscribe to monitor the status of this investigation and re-implementation?

**Comment by xubaiw** [comment]
I have created a FFI binding to `wgpu-native`, which exports most of the features of the underlying implementation.
Maybe later we can create a polyfill based on it.

repo: https://github.com/xubaiw/deno-wgpu
example: https://github.com/xubaiw/deno-wgpu/blob/main/examples/compute.ts

**Comment by goddtriffin** [comment]
Can't wait for WebGPU to be re-enabled. Currently blocking a web game idea I want to make.

**Comment by lino-levan** [comment]
Linking https://github.com/denoland/deno/pull/20812 for visibility.

**Comment by TheTrueFax** [comment]
I made a Mandelbrot renderer in webgpu.

but it only works on my local file system
not on my website.

link: [My website (kinda broken rn)](http://ttf.rf.gd/gpujs/)

**Comment by crowlKats** [comment]
Update: WebGPU has landed in Deno, and will be available in the next release on wednesday. Will keep this issue open until then.

**Comment by crowlKats** [comment]
Closing as WebGPU has relanded.
